- name: Make sure dnf-plugins.core installed
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present

- name: Install golang dependencies
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - wget
    - tar

- name: Download golang
  ansible.builtin.get_url:
    url: "{{ golang_download_url }}"
    dest: /tmp/{{ golang_file }}
    mode: '0644'

- name: Extract golang
  ansible.builtin.unarchive:
    src: /tmp/{{ golang_file }}
    dest: /usr/local
    remote_src: true

- name: Add golang to PATH
  ansible.builtin.lineinfile:
    path: /usr/local/go/bin
    line: 'export PATH=$PATH:/usr/local/go/bin'
    state: present
