- name: Importing (free) key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ vscode_microsoft_gpg_key }}"

- name: Add vscode to yum.
  ansible.builtin.blockinfile:
    path: "{{ vscode_yum_path }}"
    block: "{{ vscode_yum_path_content }}"

- name: Install vscode
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - code
