- name: Make sure that the docker package is installed
  ansible.builtin.dnf:
    name: docker
    state: present
  tags: docker

- name: Make sure that the docker compose command is installed
  ansible.builtin.dnf:
    name: docker-compose
    state: present
  tags: docker

- name: Make sure that the docker service is enabled and running
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
  tags: docker

- name: Use the docker-compose.yaml file to start the portainer container
  ansible.builtin.command: docker-compose -f /opt/portainer/docker-compose.yaml up -d
  tags: portainer
  changed_when: false
