- name: Make sure apt-transport-https is installed
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

- name: Add Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    validate_certs: false

- name: Add the repository to Apt sources
  ansible.builtin.copy:
    content: |
      deb [arch={{ ansible_architecture }} signed-by={{ docker_debian_signed_by }}]
          {{ docker_repository }} {{ ansible_distribution_release }} stable
    dest: /etc/apt/sources.list.d/docker.list
    owner: root
    group: root
    mode: '0644'

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install docker repository
  ansible.builtin.command:
    cmd: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 7EA0A9C3F273FCD8
    creates: /etc/apt/sources.list.d/docker.list

- name: Make sure docker from distro (apt) is not installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker.io
    - docker-engine
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Install docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Start and enable docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  when: ansible_user != 'root'

- name: Test docker
  ansible.builtin.command: docker --version
  register: docker_version
  changed_when: false
  failed_when: false
