- name: Make sure apt-transport-https is installed
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

- name: Install docker repository
  ansible.builtin.command:
    cmd: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 7EA0A9C3F273FCD8
    creates: /etc/apt/sources.list.d/docker.list

- name: Make sure docker from distro (apt) is not installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker.io
    - docker-engine
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Install docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Start and enable docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  when: ansible_user != 'root'
