- name: Setup essential packages
  hosts: test
  become: true
  roles:
    - update
    - zsh
  tasks:
    - name: Import essential tasks
      ansible.builtin.import_tasks: tasks/essential.yml
  handlers:
    - name: Import essential handlers
      ansible.builtin.import_tasks: handlers/essential.yml
