- name: Debian | Ensure the packages are up to date
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    update_cache: true

- name: Debian | Update packages
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
