- name: RedHat | Ensure the packages are up to date
  when: ansible_os_family == 'RedHat'
  ansible.builtin.dnf:
    update_cache: true

- name: RedHat | Update packages
  when: ansible_os_family == 'RedHat'
  ansible.builtin.dnf:
    name: '*'
    state: present
