- name: Disable ssh password authentication
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#PasswordAuthentication yes'
    line: 'PasswordAuthentication no'
  notify: Restart sshd

- name: Enable ssh passwordless sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    line: '{{ username }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
